apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maas-controller-leader-election-rolebinding
  namespace: opendatahub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: maas-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: maas-controller
  namespace: opendatahub
