apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maas

resources:
  - ../../base
  - llamastack-config.yaml
  - anthropic-api-key-secret.yaml

patches:
  - path: patches/deployment-patch.yaml
    target:
      kind: LLMInferenceService
      name: llamastack

namePrefix: anthropic-

labels:
  - pairs:
      app.kubernetes.io/instance: anthropic-llamastack
      provider: anthropic