apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm

resources:
  - ../../base
  - anthropic-api-key-secret.yaml

patches:
  - target:
      kind: LLMInferenceService
      name: llamastack
    path: patches/deployment-patch.yaml

namePrefix: anthropic-

labels:
  - pairs:
      app.kubernetes.io/instance: anthropic-llamastack
      provider: anthropic