# This kustomization.yaml is used for CRD generation.
resources:
  - bases/maas.opendatahub.io_maasauthpolicies.yaml
  - bases/maas.opendatahub.io_maasmodelrefs.yaml
  - bases/maas.opendatahub.io_maassubscriptions.yaml
