apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm

resources:
  - ../../base
  - gemini-api-key-secret.yaml

patches:
  - target:
      kind: LLMInferenceService
      name: llamastack
    path: patches/deployment-patch.yaml

namePrefix: gemini-

labels:
  - pairs:
      app.kubernetes.io/instance: gemini-llamastack
      provider: gemini
