apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - llamastack.yaml

labels:
  - pairs:
      app.kubernetes.io/name: llamastack
      app.kubernetes.io/component: inference-service