apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendatahub

resources:
  - ../../base/maas-api/overlays/tls
  - ../../../maas-controller/config/default
  - ../../base/policies
