apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterrole.yaml
- clusterrole_binding.yaml
- service_account.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
