apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This requires Kuadrant/Red Hat Connectivity Link to be installed
resources:
  - auth-policy.yaml
  - auth-policy-token-issuance.yaml
