apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/maas-api  # maas-api with HTTP (default)
  - ../../../maas-controller/config/default
  - ../../base/policies  # Gateway-level policies (rate limits)

